    <option value=""> Agua Santa del Yuna, Duarte </option>
    <option value=""> Altamira, Puerto Plata </option>
    <option value=""> Amiama Gómez, Azua </option>
    <option value=""> Amina, Provincia Valverde </option>
    <option value=""> Angelina, Sánchez Ramírez </option>
    <option value=""> Arenoso, Duarte </option>
    <option value=""> Arroyo Al Medio, María Trinidad Sánchez </option>
    <option value=""> Arroyo Barril, Samaná </option>
    <option value=""> Arroyo Cano, San Juan </option>
    <option value=""> Arroyo Dulce, Barahona </option>
    <option value=""> Arroyo Salado, María Trinidad Sánchez </option>
    <option value=""> Arroyo Toro - Masipedro, Monseñor Nouel </option>
    <option value=""> Azua, Azua </option>
    <option value=""> Bahoruco, Barahona </option>
    <option value=""> Baitoa, Santiago </option>
    <option value=""> Bajos De Haina, San Cristóbal </option>
    <option value=""> Baní, Peravia </option>
    <option value=""> Barahona, Barahona </option>
    <option value=""> Barraquito, Duarte </option>
    <option value=""> Barreras, Azua </option>
    <option value=""> Barro Arriba, Azua </option>
    <option value=""> Batey 8, Independencia </option>
    <option value=""> Batista, San Juan </option>
    <option value=""> Bayaguana, Monte Plata </option>
    <option value=""> Bayahíbe, La Altagracia </option>
    <option value=""> Belloso, Puerto Plata </option>
    <option value=""> Blanco, Hermanas Mirabal </option>
    <option value=""> Boca Chica, Santo Domingo </option>
    <option value=""> Boca De Mao, Provincia Valverde </option>
    <option value=""> Boca de Cachón, Independencia </option>
    <option value=""> Boca de Yuma, La Altagracia </option>
    <option value=""> Bohechío, San Juan </option>
    <option value=""> Bonao, Monseñor Nouel </option>
    <option value=""> Boyá, Monte Plata </option>
    <option value=""> Buena Vista, La Vega </option>
    <option value=""> Bánica, Elías Piña </option>
    <option value=""> Caballero, Sánchez Ramírez </option>
    <option value=""> Cabarete, Puerto Plata </option>
    <option value=""> Cabeza de Toro, Bahoruco </option>
    <option value=""> Cabral, Barahona </option>
    <option value=""> Cabrera, María Trinidad Sánchez </option>
    <option value=""> Caleta, La Romana </option>
    <option value=""> Cambita El Pueblecito, San Cristóbal </option>
    <option value=""> Cambita Garabitos, San Cristóbal </option>
    <option value=""> Cana Chapetón, Monte Cristi </option>
    <option value=""> Canabacoa, Santiago </option>
    <option value=""> Canca La Piedra, Santiago </option>
    <option value=""> Canca La Reyna, Espaillat </option>
    <option value=""> Canoa, Barahona </option>
    <option value=""> Capotillo, Dajabón </option>
    <option value=""> Carrera De Yeguas, San Juan </option>
    <option value=""> Castañuelas, Monte Cristi </option>
    <option value=""> Castillo, Duarte </option>
    <option value=""> Catalina, Peravia </option>
    <option value=""> Cayetano Germosén, Espaillat </option>
    <option value=""> Cañongo, Dajabón </option>
    <option value=""> Cenoví, Duarte </option>
    <option value=""> Cevicos, Sánchez Ramírez </option>
    <option value=""> Chirino, Monte Plata </option>
    <option value=""> Clavellina, Azua </option>
    <option value=""> Comedero Arriba, Sánchez Ramírez </option>
    <option value=""> Comendador, Elías Piña </option>
    <option value=""> Constanza, La Vega </option>
    <option value=""> Consuelo, San Pedro de Macorís </option>
    <option value=""> Cotuí, Sánchez Ramírez </option>
    <option value=""> Cristo Rey de Guaraguao, Duarte </option>
    <option value=""> Cristóbal, Independencia </option>
    <option value=""> Cruce De Guayacanes, Provincia Valverde </option>
    <option value=""> Cumayasa, La Romana </option>
    <option value=""> Dajabón, Dajabón </option>
    <option value=""> Derrumbadero, San Juan </option>
    <option value=""> Don Juan Rodríguez, La Vega </option>
    <option value=""> Don Juan, Monte Plata </option>
    <option value=""> Doña Ana, San Cristóbal </option>
    <option value=""> Doña Emma Balaguer Viuda Vallejo, Azua </option>
    <option value=""> Duvergé, Independencia </option>
    <option value=""> El Aguacate, Duarte </option>
    <option value=""> El Cachón, Barahona </option>
    <option value=""> El Caimito, Santiago </option>
    <option value=""> El Carretón, Peravia </option>
    <option value=""> El Carril, San Cristóbal </option>
    <option value=""> El Cedro, El Seibo </option>
    <option value=""> El Cercado, San Juan </option>
    <option value=""> El Estrecho De Luperón Omar Bross, Puerto Plata </option>
    <option value=""> El Factor, María Trinidad Sánchez </option>
    <option value=""> El Higüerito, Espaillat </option>
    <option value=""> El Limonal, Peravia </option>
    <option value=""> El Limón, Independencia </option>
    <option value=""> El Limón, Samaná </option>
    <option value=""> El Limón, Santiago </option>
    <option value=""> El Llano, Elías Piña </option>
    <option value=""> El Naranjal, San José de Ocoa </option>
    <option value=""> El Palmar, Bahoruco </option>
    <option value=""> El Peñón, Barahona </option>
    <option value=""> El Pinar, San José de Ocoa </option>
    <option value=""> El Pino, Dajabón </option>
    <option value=""> El Pozo, María Trinidad Sánchez </option>
    <option value=""> El Puerto, San Pedro de Macorís </option>
    <option value=""> El Ranchito, La Vega </option>
    <option value=""> El Rosario, Azua </option>
    <option value=""> El Rosario, San Juan </option>
    <option value=""> El Rubio, Santiago </option>
    <option value=""> El Salado, Bahoruco </option>
    <option value=""> El Seibo, El Seibo </option>
    <option value=""> El Valle, Hato Mayor </option>
    <option value=""> Elupina Cordero De Las Cañitas, Hato Mayor </option>
    <option value=""> Enriquillo, Barahona </option>
    <option value=""> Esperanza, Provincia Valverde </option>
    <option value=""> Estebanía, Azua </option>
    <option value=""> Estero Hondo, Puerto Plata </option>
    <option value=""> Eugenio María de Hostos, Duarte </option>
    <option value=""> Fantino, Sánchez Ramírez </option>
    <option value=""> Fondo Negro, Barahona </option>
    <option value=""> Fundación, Barahona </option>
    <option value=""> Galván, Bahoruco </option>
    <option value=""> Ganadero, Azua </option>
    <option value=""> Gaspar Hernández, Espaillat </option>
    <option value=""> Gautier, San Pedro de Macorís </option>
    <option value=""> Gonzalo, Monte Plata </option>
    <option value=""> Gualete, Puerto Plata </option>
    <option value=""> Guananico, Puerto Plata </option>
    <option value=""> Guanito, Elías Piña </option>
    <option value=""> Guanito, San Juan </option>
    <option value=""> Guatapanal, Provincia Valverde </option>
    <option value=""> Guayabal, Azua </option>
    <option value=""> Guayabal, Independencia </option>
    <option value=""> Guayabal, Santiago </option>
    <option value=""> Guayabo Dulce, Hato Mayor </option>
    <option value=""> Guayabo, Elías Piña </option>
    <option value=""> Guayacanes, San Pedro de Macorís </option>
    <option value=""> Guaymate, La Romana </option>
    <option value=""> Guayubín, Monte Cristi </option>
    <option value=""> Hatillo Palma, Monte Cristi </option>
    <option value=""> Hatillo, San Cristóbal </option>
    <option value=""> Hato Damas, San Cristóbal </option>
    <option value=""> Hato Del Padre, San Juan </option>
    <option value=""> Hato Del Yaque, Santiago </option>
    <option value=""> Hato Mayor, Hato Mayor </option>
    <option value=""> Hato Nuevo Cortés, Azua </option>
    <option value=""> Hato Viejo, Santo Domingo </option>
    <option value=""> Hernando Alonzo, Sánchez Ramírez </option>
    <option value=""> Higüey, La Altagracia </option>
    <option value=""> Hondo Valle, Elías Piña </option>
    <option value=""> Imbert, Puerto Plata </option>
    <option value=""> Jaibón (Pueblo Nuevo), Provincia Valverde </option>
    <option value=""> Jaibón, Provincia Valverde </option>
    <option value=""> Jamao Afuera, Hermanas Mirabal </option>
    <option value=""> Jamao Al Norte, Espaillat </option>
    <option value=""> Jaquimeyes, Barahona </option>
    <option value=""> Jarabacoa, La Vega </option>
    <option value=""> Jaya, Duarte </option>
    <option value=""> Jayaco, Monseñor Nouel </option>
    <option value=""> Jicomé, Provincia Valverde </option>
    <option value=""> Jima Abajo, La Vega </option>
    <option value=""> Jimaní, Independencia </option>
    <option value=""> Joba Arriba, Espaillat </option>
    <option value=""> Jorjillo, San Juan </option>
    <option value=""> José Contreras, Espaillat </option>
    <option value=""> José Francisco Peña Gómez, Pedernales </option>
    <option value=""> Juan Adrián, Monseñor Nouel </option>
    <option value=""> Juan De Herrera, San Juan </option>
    <option value=""> Juan López, Espaillat </option>
    <option value=""> Juan Santiago, Elías Piña </option>
    <option value=""> Juancho, Pedernales </option>
    <option value=""> Juma Bejucal, Monseñor Nouel </option>
    <option value=""> Juncalito, Santiago </option>
    <option value=""> Jánico, Santiago </option>
    <option value=""> Jínova, San Juan </option>
    <option value=""> La Bija, Sánchez Ramírez </option>
    <option value=""> La Caleta, Santo Domingo </option>
    <option value=""> La Canela, Santiago </option>
    <option value=""> La Caya, Provincia Valverde </option>
    <option value=""> La Ciénaga, Barahona </option>
    <option value=""> La Ciénaga, San José de Ocoa </option>
    <option value=""> La Colonia, Independencia </option>
    <option value=""> La Cuaba, Santo Domingo </option>
    <option value=""> La Cuchilla, San Cristóbal </option>
    <option value=""> La Cuesta, Santiago </option>
    <option value=""> La Cueva, Sánchez Ramírez </option>
    <option value=""> La Descubierta, Independencia </option>
    <option value=""> La Entrada, María Trinidad Sánchez </option>
    <option value=""> La Gina, El Seibo </option>
    <option value=""> La Guáyiga, Santo Domingo </option>
    <option value=""> La Guázara, Barahona </option>
    <option value=""> La Isabela, Puerto Plata </option>
    <option value=""> La Jagua, San Juan </option>
    <option value=""> La Jaiba, Puerto Plata </option>
    <option value=""> La Mata, Sánchez Ramírez </option>
    <option value=""> La Ortega, Espaillat </option>
    <option value=""> La Otra Banda, La Altagracia </option>
    <option value=""> La Peña, Duarte </option>
    <option value=""> La Romana, La Romana </option>
    <option value=""> La Sabina, La Vega </option>
    <option value=""> La Salvia - Los Quemados, Monseñor Nouel </option>
    <option value=""> La Siembra, Azua </option>
    <option value=""> La Vega, La Vega </option>
    <option value=""> La Victoria, Santo Domingo </option>
    <option value=""> Laguna Salada, Provincia Valverde </option>
    <option value=""> Las Barías, Peravia </option>
    <option value=""> Las Barías-La Estancia, Azua </option>
    <option value=""> Las Charcas De María Nova, San Juan </option>
    <option value=""> Las Charcas, Azua </option>
    <option value=""> Las Clavellinas, Bahoruco </option>
    <option value=""> Las Coles, Duarte </option>
    <option value=""> Las Galeras, Samaná </option>
    <option value=""> Las Gordas, María Trinidad Sánchez </option>
    <option value=""> Las Guáranas, Duarte </option>
    <option value=""> Las Lagunas De Nisibón, La Altagracia </option>
    <option value=""> Las Lagunas, Azua </option>
    <option value=""> Las Lagunas, Espaillat </option>
    <option value=""> Las Lomas, Azua </option>
    <option value=""> Las Maguanas-Hato Nuevo, San Juan </option>
    <option value=""> Las Matas De Farfán, San Juan </option>
    <option value=""> Las Matas De Santa Cruz, Monte Cristi </option>
    <option value=""> Las Palomas, Santiago </option>
    <option value=""> Las Placetas, Santiago </option>
    <option value=""> Las Salinas, Barahona </option>
    <option value=""> Las Taranas, Duarte </option>
    <option value=""> Las Terrenas, Samaná </option>
    <option value=""> Las Yayas de Viajama, Azua </option>
    <option value=""> Las Zanjas, San Juan </option>
    <option value=""> Licey Al Medio, Santiago </option>
    <option value=""> Loma De Cabrera, Dajabón </option>
    <option value=""> Los Alcarrizos, Santo Domingo </option>
    <option value=""> Los Botados, Monte Plata </option>
    <option value=""> Los Cacaos, San Cristóbal </option>
    <option value=""> Los Fríos, Azua </option>
    <option value=""> Los Hidalgos, Puerto Plata </option>
    <option value=""> Los Jovillos, Azua </option>
    <option value=""> Los Llanos, San Pedro de Macorís </option>
    <option value=""> Los Patos, Barahona </option>
    <option value=""> Los Ríos, Bahoruco </option>
    <option value=""> Los Toros, Azua </option>
    <option value=""> Luperón, Puerto Plata </option>
    <option value=""> Maimón, Monseñor Nouel </option>
    <option value=""> Maimón, Puerto Plata </option>
    <option value=""> Maizal, Provincia Valverde </option>
    <option value=""> Majagual, Monte Plata </option>
    <option value=""> Mamá Tingó, Monte Plata </option>
    <option value=""> Manabao, La Vega </option>
    <option value=""> Manuel Bueno, Dajabón </option>
    <option value=""> Mao, Provincia Valverde </option>
    <option value=""> Mata Palacio, Hato Mayor </option>
    <option value=""> Matanzas, Peravia </option>
    <option value=""> Matayaya, San Juan </option>
    <option value=""> Medina, San Cristóbal </option>
    <option value=""> Mella, Independencia </option>
    <option value=""> Mena, Bahoruco </option>
    <option value=""> Miches, El Seibo </option>
    <option value=""> Moca, Espaillat </option>
    <option value=""> Monción, Santiago Rodríguez </option>
    <option value=""> Monserrate (Montserrat), Bahoruco </option>
    <option value=""> Monte Bonito, Azua </option>
    <option value=""> Monte Cristi, Monte Cristi </option>
    <option value=""> Monte Plata, Monte Plata </option>
    <option value=""> Monte de la Jagua, Espaillat </option>
    <option value=""> Nagua, María Trinidad Sánchez </option>
    <option value=""> Navas, Puerto Plata </option>
    <option value=""> Neiba, Bahoruco </option>
    <option value=""> Nizao - Las Auyamas, San José de Ocoa </option>
    <option value=""> Nizao, Peravia </option>
    <option value=""> Oviedo, Pedernales </option>
    <option value=""> Padre las Casas, Azua </option>
    <option value=""> Palmar Arriba, Santiago </option>
    <option value=""> Palmar de Ocoa, Azua </option>
    <option value=""> Palmarejo Villa Linda, Santo Domingo </option>
    <option value=""> Palo Alto, Barahona </option>
    <option value=""> Palo Verde, Monte Cristi </option>
    <option value=""> Pantoja, Santo Domingo </option>
    <option value=""> Paradero, Provincia Valverde </option>
    <option value=""> Paraíso, Barahona </option>
    <option value=""> Partido, Dajabón </option>
    <option value=""> Paya, Peravia </option>
    <option value=""> Pedernales, Pedernales </option>
    <option value=""> Pedro Brand, Santo Domingo </option>
    <option value=""> Pedro Corto, San Juan </option>
    <option value=""> Pedro García, Santiago </option>
    <option value=""> Pedro Santana, Elías Piña </option>
    <option value=""> Pedro Sánchez, El Seibo </option>
    <option value=""> Pepillo Salcedo (Manzanillo), Monte Cristi </option>
    <option value=""> Peralta, Azua </option>
    <option value=""> Peralvillo, Monte Plata </option>
    <option value=""> Pescadería, Barahona </option>
    <option value=""> Piedra Blanca, Monseñor Nouel </option>
    <option value=""> Pimentel, Duarte </option>
    <option value=""> Pizarrete, Peravia </option>
    <option value=""> Platanal, Sánchez Ramírez </option>
    <option value=""> Polo, Barahona </option>
    <option value=""> Postrer Río, Independencia </option>
    <option value=""> Presidente Don Antonio Guzmán Fernández, Duarte </option>
    <option value=""> Proyecto 2-C, Azua </option>
    <option value=""> Proyecto 4, Azua </option>
    <option value=""> Pueblo Viejo, Azua </option>
    <option value=""> Puerto Plata, Puerto Plata </option>
    <option value=""> Puerto Viejo, Azua </option>
    <option value=""> Puñal, Santiago </option>
    <option value=""> Quisqueya, San Pedro de Macorís </option>
    <option value=""> Quita Coraza, Barahona </option>
    <option value=""> Quita Sueño, San Cristóbal </option>
    <option value=""> Quita Sueño, Sánchez Ramírez </option>
    <option value=""> Ramón Santana, San Pedro de Macorís </option>
    <option value=""> Rancho Arriba, San José de Ocoa </option>
    <option value=""> Rancho de la Guardia, Elías Piña </option>
    <option value=""> Restauración, Dajabón </option>
    <option value=""> Rincón, La Vega </option>
    <option value=""> Río Grande, Puerto Plata </option>
    <option value=""> Río Limpio, Elías Piña </option>
    <option value=""> Río San Juan, María Trinidad Sánchez </option>
    <option value=""> Río Verde Arriba, La Vega </option>
    <option value=""> Sabana Alta, San Juan </option>
    <option value=""> Sabana Buey, Peravia </option>
    <option value=""> Sabana Cruz, Elías Piña </option>
    <option value=""> Sabana De La Mar, Hato Mayor </option>
    <option value=""> Sabana Del Puerto, Monseñor Nouel </option>
    <option value=""> Sabana Grande De Boyá, Monte Plata </option>
    <option value=""> Sabana Grande De Palenque, San Cristóbal </option>
    <option value=""> Sabana Grande, Duarte </option>
    <option value=""> Sabana Higüero, Elías Piña </option>
    <option value=""> Sabana Iglesia, Santiago </option>
    <option value=""> Sabana Larga, Elías Piña </option>
    <option value=""> Sabana Larga, San José de Ocoa </option>
    <option value=""> Sabana Yegua, Azua </option>
    <option value=""> Sabaneta De Yásica, Puerto Plata </option>
    <option value=""> Sabaneta, San Juan </option>
    <option value=""> Salcedo, Hermanas Mirabal </option>
    <option value=""> Samaná, Samaná </option>
    <option value=""> San Antonio De Guerra, Santo Domingo </option>
    <option value=""> San Cristóbal, San Cristóbal </option>
    <option value=""> San Francisco De Jacagua, Santiago </option>
    <option value=""> San Francisco De Macorís, Duarte </option>
    <option value=""> San Francisco-Vicentillo, El Seibo </option>
    <option value=""> San Gregorio De Nigua, San Cristóbal </option>
    <option value=""> San Ignacio De Sabaneta, Santiago Rodríguez </option>
    <option value=""> San José De Las Matas, Santiago </option>
    <option value=""> San José De Matanzas, María Trinidad Sánchez </option>
    <option value=""> San José De Ocoa, San José de Ocoa </option>
    <option value=""> San José Del Puerto, San Cristóbal </option>
    <option value=""> San Juan, San Juan </option>
    <option value=""> San Luis, Santo Domingo </option>
    <option value=""> San Pedro De Macorís, San Pedro de Macorís </option>
    <option value=""> San Rafael del Yuma, La Altagracia </option>
    <option value=""> San Víctor, Espaillat </option>
    <option value=""> Santa Bárbara El 6, Bahoruco </option>
    <option value=""> Santa Lucía, El Seibo </option>
    <option value=""> Santa María, Monte Cristi </option>
    <option value=""> Santana, Bahoruco </option>
    <option value=""> Santana, Peravia </option>
    <option value=""> Santiago De La Cruz, Dajabón </option>
    <option value=""> Santiago, Santiago </option>
    <option value=""> Santo Domingo Este, Santo Domingo </option>
    <option value=""> Santo Domingo Norte, Santo Domingo </option>
    <option value=""> Santo Domingo Oeste, Santo Domingo </option>
    <option value=""> Santo Domingo de Guzmán, Distrito Nacional </option>
    <option value=""> Sosúa, Puerto Plata </option>
    <option value=""> Sánchez, Samaná </option>
    <option value=""> Tamayo, Bahoruco </option>
    <option value=""> Tamboril, Santiago </option>
    <option value=""> Taveras, La Vega </option>
    <option value=""> Tenares, Hermanas Mirabal </option>
    <option value=""> Tireo, La Vega </option>
    <option value=""> Tábara Abajo, Azua </option>
    <option value=""> Tábara Arriba, Azua </option>
    <option value=""> Uvilla, Bahoruco </option>
    <option value=""> Vallejuelo, San Juan </option>
    <option value=""> Vengan A Ver, Independencia </option>
    <option value=""> Veragua, Espaillat </option>
    <option value=""> Verón Punta Cana (Incluye Bávaro), La Altagracia </option>
    <option value=""> Vicente Noble, Barahona </option>
    <option value=""> Villa Altagracia, San Cristóbal </option>
    <option value=""> Villa Bisonó (Navarrete), Santiago </option>
    <option value=""> Villa Central, Barahona </option>
    <option value=""> Villa De Sonador, Monseñor Nouel </option>
    <option value=""> Villa Elisa, Monte Cristi </option>
    <option value=""> Villa Fundación, Peravia </option>
    <option value=""> Villa González, Santiago </option>
    <option value=""> Villa Hermosa, La Romana </option>
    <option value=""> Villa Isabela, Puerto Plata </option>
    <option value=""> Villa Jaragua, Bahoruco </option>
    <option value=""> Villa Los Almácigos, Santiago Rodríguez </option>
    <option value=""> Villa Magante, Espaillat </option>
    <option value=""> Villa Montellano, Puerto Plata </option>
    <option value=""> Villa Riva, Duarte </option>
    <option value=""> Villa Sombrero, Peravia </option>
    <option value=""> Villa Tapia, Hermanas Mirabal </option>
    <option value=""> Villa Vásquez, Monte Cristi </option>
    <option value=""> Villarpando, Azua </option>
    <option value=""> Yaguate, San Cristóbal </option>
    <option value=""> Yaque, San Juan </option>
    <option value=""> Yerba Buena, Hato Mayor </option>
    <option value=""> Yásica Arriba, Puerto Plata </option>
    <option value=""> Zambrana Abajo, Sánchez Ramírez </option>
    <option value=""> República de Haití, Haití </option>
    

